ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Models/Enums/Genders.cs
namespace ASP.NetCoreMVC_EX1_.Models.Enums
{
    public enum Gender
    {
        Male,
        Female
    }
}

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Models/ErrorViewModel.cs
namespace ASP.NetCoreMVC_EX1_.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Models/RookieModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using ASP.NetCoreMVC_EX1_.Models.Enums;

namespace ASP.NetCoreMVC_EX1_.Models
{   

    public class RookieModel
    {
        [DisplayName("ID")]
        public int RookieId { get; set; }
        [DisplayName("First Name")]
        [Required]
        public string FirstName { get; set; }
        [Required]
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        public string FullName { get { return $"{FirstName} {LastName}"; }}
        [Required]
        [DataType(DataType.EmailAddress)]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Email is not valid!")]
        public string Email { get; set; }
        [Required]
        public Gender Gender { get; set; }
        [DisplayName("Date Of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}",ApplyFormatInEditMode = true)]
        public DateTime DoB { get; set; }
        [Required]
        [DisplayName("Phone Number")]
        [RegularExpression(@"^([0-9]{9,})$", ErrorMessage = "Number digit only!, at least 9")]
        public string PhoneNumber { get; set; }
        public string Age
        {
            get
            {
                DateTime now = DateTime.Now;
                int age = now.Year - DoB.Year;
                if (DoB > now.AddYears(-age))
                {
                    age--;
                };
                return age.ToString();
            }
        }
        [Required]
        [DisplayName("Birth Place")]
        public string BirthPlace { get; set; }
        public Boolean Graduated { get; set; }
    }
}

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ASP.NetCoreMVC_EX1_.Models;

namespace ASP.NetCoreMVC_EX1_.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Controllers/RookiesController.cs
using Microsoft.AspNetCore.Mvc;
using ASP.NetCoreMVC_EX1_.Models;
using ASP.NetCoreMVC_EX1_.Services;

namespace ASP.NetCoreMVC_EX1_.Controllers
{
    public class RookiesController : Controller
    {
        private readonly IRookiesService _rookiesService;
        public RookiesController(IRookiesService rookiesService)
        {
            _rookiesService = rookiesService;
        }

        public async Task<IActionResult> Index()
        {
            var rookies = await _rookiesService.GetAllRookie();
            return View(rookies);
        }
        public async Task<IActionResult> ViewMaleRookies()
        {
            var rookies = await _rookiesService.GetMaleRookieList();
            return View(rookies);
        }

        public async Task<IActionResult> ViewFullName()
        {
            var rookies = await _rookiesService.GetFullNameList();
            ViewBag.FullName = rookies;
            return View();
        }

        public async Task<IActionResult> ViewOldestRookie()
        {
            var oldestRookie = await _rookiesService.GetOldestRookie();
            return View(oldestRookie);
        }

        [HttpGet("Nashtech/Rookies/ViewByBirthYear/")]
        public async Task<IActionResult> ViewByBirthYear(string condition)
        {
            var rookies = await _rookiesService.GetRookieByBirthYear(condition);
            return View(rookies);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RookieModel rookie)
        {
            if (ModelState.IsValid)
            {
                var result = await _rookiesService.CreateRookie(rookie);
                return RedirectToAction("Index");
            }
            return View(rookie);
        }

        public async Task<FileContentResult> ExportExcelButton()
        {
            return await _rookiesService.ExportExcel();
        }
    }
}

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Rookies/Create.cshtml
@model ASP.NetCoreMVC_EX1_.Models.RookieModel

@{
    Layout = "_Layout";
}

<h1>NEW ROOKIE </h1>

<a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Back</a>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">

            <partial name = "_Form">
                
        </form>
    </div>
</div>

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Rookies/Index.cshtml
@model IEnumerable<ASP.NetCoreMVC_EX1_.Models.RookieModel>

@{
    Layout = "_Layout";
}

<body>
    <h1>THE ROOKIES</h1>
    <div style="display:flex">
        <div style="flex-basis:50%">
            <a href="@Url.ActionLink("Create", "Rookies")" class="btn btn-success"><i class="fa fa-user-plus"></i>
                Create</a>
        </div>
        <div style="flex-basis:50%,text-align:center">
            <form method="post" asp-controller="Rookies" asp-action="ExportExcelButton">
                <input class="btn btn-primary" type="submit" value="Export" />
            </form>
        </div>
    </div>

    <partial name="_View">
    
    <div>
        <div class="btn-group dropright">
            <button class="btn btn-secondary " type="button" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="true">
                Options
            </button> 
            <div class="dropdown">
                <a class="dropdown-item" href="@Url.ActionLink("ViewMaleRookies","Rookies")">Return male rookies List</a>
                <a class="dropdown-item" href="@Url.ActionLink("ViewOldestRookie","Rookies")">Return oldest rookie</a>
                <a class="dropdown-item" href="@Url.ActionLink("ViewFullName","Rookies")">Return full name List</a>
                <a class="dropdown-item" href="@Url.ActionLink("ViewByBirthYear","Rookies", new{condition = "equal"})">Return rookies who has birth year is 2000</a>
                <a class="dropdown-item" href="@Url.ActionLink("ViewByBirthYear","Rookies", new{condition = "greater"})">Return rookies who has birth year is greater than 2000</a>
                <a class="dropdown-item" href="@Url.ActionLink("ViewByBirthYear","Rookies",new{condition = "less"})">Return rookies who has birth year is less than 2000</a>
             </div>
        </div>
    </div>
</body>

@if (TempData["DeleteSuccess"] != null)
{
     <p class="alert alert-success" id="successMessage">@TempData["DeleteSuccess"] @ViewData["memberName"] </p>
}

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Rookies/ViewByBirthYear.cshtml
@model IEnumerable<ASP.NetCoreMVC_EX1_.Models.RookieModel>

@{
    Layout = "_Layout";
}

<body>
    <h1>VIEW ROOKIES BY BIRTH YEAR </h1>
    <a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Back</a>
    
    <partial name="_View"></partial>
    
</body>

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Rookies/ViewFullName.cshtml
@{
    Layout = "_Layout";
}
<body> 
    <a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Back</a>
    <h1>Full Name ROOKIES </h1>
    <ul class="list-group">
        @foreach (var item in ViewBag.FullName)
        {
            <li class="list-group-item">@item</li>
        } 
    </ul>
    </table>
</body>

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Rookies/ViewMaleRookies.cshtml
@model IEnumerable<ASP.NetCoreMVC_EX1_.Models.RookieModel>

@{
    Layout = "_Layout";
}

<body>
    <h1>MALE ROOKIES LIST</h1>
    <a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Back</a>
    
    <partial name="_View"></partial>
    
</body>

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Rookies/ViewOldestRookie.cshtml
@model ASP.NetCoreMVC_EX1_.Models.RookieModel

@{
  Layout = "_Layout";
}

<body>
  <h1>OLDEST ROOKIE</h1>
  <a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Back</a>
  
  <partial name = "_Card">
    
</body>

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Shared/_Card.cshtml
 @model ASP.NetCoreMVC_EX1_.Models.RookieModel
 <div class="card" style="width: 18rem;">
    <img class="card-img-top"
      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIhCBq-WV5kdxy5e-8fgzaYKejJFYOUnTt1Q&usqp=CAU"
      alt="Card image cap">
    <div class="card-body">
      <dl>
        <h5 class="card-title">@Model.FirstName @Model.LastName</h5>
        <p class="card-text">@Model.Gender</p>
        <p class="card-text">@Model.DoB.ToString("dd/MM/yyyy")</p>
        <p class="card-text">@Model.Email</p>
        <p class="card-text">@Model.PhoneNumber</p>
        <p class="card-text">@{
              if (@Model.Graduated == true)
              {
                <span>Graduated</span>;
              }
              else
              {
                <span>Undergraduate</span>;
              }
            }
        </p>

      </dl>

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Shared/_Form.cshtml
@model ASP.NetCoreMVC_EX1_.Models.RookieModel
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <div class="custom-control custom-radio">
                    <input type="radio" asp-for="Gender" class="custom-radio" value="Male"/> Male
                </div>
               <div class="custom-control custom-radio">
                <input type="radio" asp-for="Gender" class="custom-radio" value="Female"/> Female
            </div>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoB" class="control-label"></label>
                <input asp-for="DoB" asp-format="{0:dd/MM/yyyy}" class="form-control" />
                <span asp-validation-for="DoB"  class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" type="number" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthPlace" class="control-label"></label>
                <input asp-for="BirthPlace" class="form-control" />
                <span asp-validation-for="BirthPlace" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="Graduated" class="control-label"></label>
                <div class="custom-control custom-radio">
                    <input type="radio" asp-for="Graduated" class="custom-radio" value=true/> Graduated
                </div>
               <div class="custom-control custom-radio">
                <input type="radio" asp-for="Graduated" class="custom-radio" value=false/> Undergraduate
            </div>
             <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NetCoreMVC_EX1_</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NetCoreMVC_EX1_.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NetCoreMVC_EX1_</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASP.NetCoreMVC_EX1_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.Net Core MVC 6.0/ASP.NetCoreMVC(EX1)/Views/Shared/_View.cshtml
   @model IEnumerable<ASP.NetCoreMVC_EX1_.Models.RookieModel>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th class="text-nowrap">Full Name</th>
                <th class="text-nowrap">@Html.DisplayNameFor(model => model.Gender)</th>
                <th class="text-nowrap">@Html.DisplayNameFor(model => model.Email)</th>
                <th class="text-nowrap">@Html.DisplayNameFor(model => model.DoB)</th>
                <th class="text-nowrap">@Html.DisplayNameFor(model => model.PhoneNumber)</th>
                <th class="text-nowrap">@Html.DisplayNameFor(model => model.BirthPlace)</th>
                <th class="text-nowrap">@Html.DisplayNameFor(model => model.Graduated)</th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-nowrap">@Html.DisplayFor(modelItem => item.FirstName)
                    @Html.DisplayFor(modelItem => item.LastName)</td>
                <td>@Html.DisplayFor(modelItem => item.Gender)</td>
                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                <td>@Html.DisplayFor(modelItem => item.DoB) - @Html.DisplayFor(modelItem => item.Age)</td>
                <td>@Html.DisplayFor(modelItem => item.PhoneNumber)</td>
                <td>@Html.DisplayFor(modelItem => item.BirthPlace)</td>
                <td>@Html.DisplayFor(modelItem => item.Graduated)</td>
              
            </tr>
        }
    </table>